# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

<<<<<<< HEAD
InfoDes_cpp <- function(par, des, n_alts) {
    .Call('_idefix_InfoDes_cpp', PACKAGE = 'idefix', par, des, n_alts)
=======
det_cpp <- function(set) {
    .Call('_idefix_det_cpp', PACKAGE = 'idefix', set)
}

InfoDes_cpp <- function(par, des, n_alts, utbal = FALSE) {
    .Call('_idefix_InfoDes_cpp', PACKAGE = 'idefix', par, des, n_alts, utbal)
>>>>>>> fe420387d86d4f6ff762f2809d2b1713bfc6b6eb
}

det_cpp <- function(set) {
    .Call('_idefix_det_cpp', PACKAGE = 'idefix', set)
}

